apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: stream-sorter
spec:
  limits:
    readBatchSize: 1
  vertices:
    - name: input-one
      scale:
        min: 1
        max: 1
      source:
        generator:
          rpu: 10
          keyCount: 10
          duration: 20s
    - name: input-two
      scale:
        min: 1
        max: 1
      source:
        generator:
          rpu: 10
          keyCount: 10
          duration: 20s
    - name: py-accum
      udf:
        container:
          image: 192.168.21.17:30003/dci-community-general/streamsorter:v0.10.0
          imagePullPolicy: Always
          env:
            - name: PYTHONDEBUG
              value: "true"
        groupBy:
          window:
            accumulator:
              timeout: 10s
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 1Gi
#             storageClassName: local-storage
    - name: py-sink
      scale:
        min: 1
        max: 1
      sink:
        log: {}
  edges:
    - from: input-one
      to: py-accum
    - from: input-two
      to: py-accum
    - from: py-accum
      to: py-sink
